#config view resolverspring:
spring:
#    static-path-pattern: /static/**
  #config datasource(mysql)
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql:///usermanagement?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
  #config MongoDB
#  data:
#    mogodb:
#      uri: mongodb://localhost:27017/
  # config redis
#  redis:
#    database:
#    host: 127.0.0.1
#    port: 6379
#    pool:
#      max-active: 8
#      max-wait: -1
#      max-idle: 8
#      min-idle: 0
#    timeout: 0
    #config druid
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM DUAL
#config thymeleaf
  thymeleaf:
    mode: HTML
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:/templates/
  # config file upload
#  http:
#    multipart:
#      # one file
#      maxFileSize: 1048576
#      # all file
#      maxRequestSize: 10485760
#    # config character encoding
#    encoding:
#      charset: UTF-8
#      force: true
#      enabled: true
# config mybatist xml
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.tian.boot.entity
  # config server port
server:
  port: 8443
  ssl:
    key-store: https.keystore
    key-store-password: 950219
    key-store-type: JKS
    key-alias: tomcat
# config pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params-count: count=countSql

logging:
  file: logs/UserManage_dev.log
  level:
    org.springframework.web: debug
    root: info
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
